In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [31]:
df=pd.read_csv('/content/multivalue linear reg.csv')
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000
5  4100      6.0    8  810000

In [ ]:
df.bedroom.median()


4.0

In [41]:
df.bedroom=df.bedroom.fillna(df.bedroom.median())
df

AttributeError: 'DataFrame' object has no attribute 'bedroom'

In [42]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

KeyError: "['price'] not found in axis"

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540396

498408.251574024

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
 112.06244194*2500 + 23388.88007794*4 + -3231.71790863*5 + 221323.00186540396

578876.0374840139

In [63]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n


ModuleNotFoundError: No module named 'word2number'

In [65]:
!pip install word2number
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [68]:
d=pd.read_csv('/content/hiring.csv')
d

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [70]:
d.experience=d.experience.fillna('zero')
d

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [74]:
d.experience=d.experience.apply(w2n.word_to_num)
d

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [76]:

d.experience = d.experience.astype(str).apply(w2n.word_to_num)
d

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [79]:
import math
median_test_score = math.floor(df['test_score'].mean())
median_test_score

7

In [81]:
d['test_score'] = d['test_score'].fillna(median_test_score)
d

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [83]:
reg = linear_model.LinearRegression()
reg.fit(d[['experience','test_score','interview_score']],d['salary'])

LinearRegression()

In [85]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [87]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [88]:
2922.26901502*2+2221.30909959*9+2147.48256637*6+14992.65144669314

53713.86677126314